### ISSUE TITLE
Add non minified file

### ISSUE THREAD

**Issue by petk** [rcodex/VeRy.js#2]
Currently there is only minified version of the main file in the repository, which makes it hard to impossible to work on in development mode. It is true that many editors have beautification functionalities, but for the sake of readability it is important to have non minified version also. When [releasing versions](https://github.com/rcodex/VeRy.js/releases) the minified version can be added for example.

**Comment by rcodex** [comment]
Updated Un minified File

**Comment by petk** [comment]
Nice. Closing issue as resolved. :+1:
